apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: workspace
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: busybox
    name: busybox
  terminationGracePeriodSeconds: 5  # Time to wait before moving from a TERM signal to the pod's main process to a KILL signal.