apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: workspace
spec:
  containers:
  - name: nginx
    image: nginx
    command: [ "/bin/sh", "-c", "echo 'Starting up'; trap 'echo Received Terminating signal' QUIT ; trap 'echo Received TERM signal' TERM; while true; do echo $(date) 'Hello, World!'; sleep 1; done"]
    lifecycle:
      preStop:
        exec:
          command:
          - sh
          - -c
          - |
            curl localhost:80
            sleep 60
            curl localhost:80
  terminationGracePeriodSeconds: 600  # Time to wait before moving from a TERM signal to the pod's main process to a KILL signal.
