apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: workspace
spec:
  containers:
  - name: nginx
    image: nginx
    lifecycle:
      preStop:
        exec:
          command:
          - sh
          - -c
          - |
            curl localhost:80
            sleep 5
            curl localhost:80
  terminationGracePeriodSeconds: 20  # Time to wait before moving from a TERM signal to the pod's main process to a KILL signal.
